package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import com.mycompany.Services.Abonnement_Service;
import com.mycompany.Views.Abo_NutrisionisteForm;
import com.mycompany.Views.Panier_Form;
import com.mycompany.Views.Produit_Form;
import com.mycompany.Views.Programme_nutrisionForm;
import com.mycompany.Views.Stat_AboForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
      Form hi = new Form("projet", BoxLayout.y());
         Button Produits = new Button("Produits");
           Button Panier = new Button("Panier");
             Button btn_nutisoniste = new Button("Abo Nutrisoniste");
               Button btn_coach = new Button("Abo Coach");
                    Button Programme = new Button("Programme");
          Produits.addActionListener(ll -> 
       {
           new Produit_Form(hi).show();
       }
       
       
       );
        hi.add(Produits);
            Panier.addActionListener(ll -> 
       {
         new Panier_Form(hi).show();
       }
       
       
       );
        hi.add(Panier);
           btn_nutisoniste.addActionListener(ll -> 
       {
         new Abo_NutrisionisteForm(hi).show();
       }
       
       
       );
        hi.add(btn_nutisoniste);
          btn_coach.addActionListener(ll -> 
       {
         new Panier_Form(hi).show();
       }
       
       
       );
        hi.add(btn_coach);
        
        
         Programme.addActionListener(ll -> 
       {
         new Programme_nutrisionForm(hi).show();
       }
       
       
       );
        hi.add(Programme);
         hi.getToolbar().addCommandToSideMenu("programe", null, e -> {
          new Programme_nutrisionForm(hi).show();
        });

           hi.getToolbar().addCommandToSideMenu("Stat Abo", null, e -> {
              new Stat_AboForm().createPieChartForm("Abonnment", new Abonnement_Service().StatAbo());
        });
        
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
